### ISSUE TITLE
Use JLD2 over JLD?

### ISSUE THREAD

**Issue by KristofferC** [JuliaCI/PkgBenchmark.jl#19]
https://github.com/simonster/JLD2.jl is written in pure Julia and is significantly faster than JLD and it also supports compression.
We already have an indirect dependency on JLD through BenchmarkTools so this would add one dependency.

I can do some benchmarks, look at timings and see if this would be a good idea. I am not sure if JLD2 can read files written by JLD. If it can, this should be backwards compatible.

**Comment by Evizero** [comment]
I'd be interested in those measurements if you do end up doing some (and feel like sharing them).

**Comment by ararslan** [comment]
If you're using BenchmarkTools for serialization of benchmarks, note that as of (the currently unreleased) BenchmarkTools v0.2.0, serialization is done using JSON rather than JLD. As such, the dependency on JLD is replaced by one on JSON. So you may want to consider using JSON here as well rather than switching to JLD2.

**Comment by KristofferC** [comment]
Using JSON right now.
