### ISSUE TITLE
Add functionality for exporting pretty printed results.

### ISSUE THREAD

**Issue by KristofferC** [JuliaCI/PkgBenchmark.jl#25]
Similar to how Nanosolider reports the base benchmarks. I have code extracted from Nanosolider that generates something like this: https://gist.github.com/KristofferC/61a6752025255ec0b5a4510c2e83263e. Functionality for exporting to this markdown format could be added after #24 is done. It would be cool if we could use the Github API to automatically upload the result to a gist.

**Comment by shashi** [comment]
It would be nice to preserve the hierarchy created by nested `@benchgroup` and `@bench` calls. This will require https://github.com/JuliaCI/BenchmarkTools.jl/pull/60 to get into BenchmarkTools and using `OrderedDict` in our macros.

This will allow us to print the benchmarks using `@benchgroup` name as subheadings as well.

Also, any chance we'll see the extremely pretty TimerOutputs.jl-like tables? :D

**Comment by KristofferC** [comment]
We already have the hierarchy right? It will just be in an arbitrary order. While it would be good to mirror the order the user gave the benchmarks perhaps lexograohical order could work for now?

**Comment by KristofferC** [comment]
Regarding TimerOutputs.jl, maaaybe.. :P

**Comment by shashi** [comment]
> We already have the hierarchy right?

Ah, right! It's the ordering that gets messed up. Yes, lexical order is fine for now.

**Comment by jrevels** [comment]
> This will allow us to print the benchmarks using @benchgroup name as subheadings as well. This imo is better than a flat list keyed by ["head1", "subhead1", "thing"], Jarrett doesn't agree with me though ...

Huh - don't think I ever said this? I definitely agree that hierarchal printing based on the `BenchmarkGroup` nesting would be more readable. You don't need the macro machinery for that, though.

The primary advantage to printing out the key list is that it makes [it really easy to look up benchmarks just by copy/pasting keys](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#indexing-into-a-benchmarkgroup-using-a-vector) - that's why I used it for Nanosoldier's printing. However, that need would better be met by HTML reports with actual code links. At the time, the main barrier to that was getting correct line number info from within macro calls, but I believe we now good functionality for that in Base.

The ordering issue should be fixed by https://github.com/JuliaCI/BenchmarkTools.jl/pull/60, which would allow you to use e.g. `OrderedDict`s for `BenchmarkGroup`s.

**Comment by KristofferC** [comment]
This is done now, benchmark results and comparisons can be exported to markdown. Right now I use something similar to nanosoldier. The exact output can always be iterated on.
